spring:
  application:
    name: goods
  sleuth:
    sampler:
      # 采样率 100%
      probability: 1
      # 每秒最多采样 100 个 trace
      rate: 100
  zipkin:
    sender:
      # 使用 web api 方式发送给 zipkin
      type: web
    base-url: http://172.18.16.1:9411
goods:
  price: 1499
server:
  port: 80
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:18761/eureka/,http://172.16.0.208:8761/eureka/