spring:
  application:
    name: goods
goods:
  price: 1499
server:
  port: 81
eureka:
  client:
    serviceUrl:
      defaultZone: http://node1:18761/eureka/,http://node2:18761/eureka/,http://node3:28761/eureka/