spring:
  application:
    name: order
  sleuth:
    sampler:
      # 采样率 100%
      probability: 1
      # 每秒最多采样 100 个 trace
      rate: 100
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:18761/eureka/,http://172.16.0.208:8761/eureka/