spring:
  application:
    name: order
  sleuth:
    sampler:
      # 采样率 100%
      probability: 1
      # 每秒最多采样 100 个 trace
      rate: 100
  zipkin:
    sender:
      # 使用 web api 方式发送给 zipkin
      type: web
    base-url: http://172.18.16.1:9411
server:
  port: 8080
eureka:
  instance:
    # 心跳间隔，默认值为 30s
    lease-renewal-interval-in-seconds: 5
    # 没有心跳的淘汰实践，默认值为 90s
    lease-expiration-duration-in-seconds: 15
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    # 定时刷新本地缓存时间，默认值为 30s
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://127.0.0.1:18761/eureka/,http://172.16.0.208:8761/eureka/