spring:
  application:
    name: gateway
  sleuth:
    sampler:
      # 采样率 100%
      probability: 1
      # 每秒最多采样 100 个 trace
      rate: 100
  zipkin:
    sender:
      # 使用 web api 方式发送给 zipkin
      type: web
    base-url: http://172.18.16.1:9411
  cloud:
    gateway:
      discovery:
        locator:
          # 是否从注册中心读取服务，只要你的路径中以微服务的服务名称开头，都会自动转发到该服务上去
          enabled: true
          # eureka 中服务名默认为大写 服务名大写转小写
          lowerCaseServiceId: true
server:
  port: 8088
eureka:
  instance:
    # 心跳间隔，默认值为 30s
    lease-renewal-interval-in-seconds: 5
    # 没有心跳的淘汰实践，默认值为 90s
    lease-expiration-duration-in-seconds: 15
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
  client:
    # 定时刷新本地缓存时间，默认值为 30s
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://127.0.0.1:18761/eureka/,http://172.16.0.208:8761/eureka/
