spring:
  application:
    name: zuul
  sleuth:
    sampler:
      # 采样率 100%
      probability: 1
      # 每秒最多采样 100 个 trace
      rate: 100
server:
  port: 8088
eureka:
  instance:
    # 心跳间隔，默认值为 30s
    lease-renewal-interval-in-seconds: 5
    # 没有心跳的淘汰实践，默认值为 90s
    lease-expiration-duration-in-seconds: 15
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    # 定时刷新本地缓存时间，默认值为 30s
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://127.0.0.1:18761/eureka/,http://172.16.0.208:8761/eureka/
CROS: true
zuul:
  host:
    connect-timeout-millis: 600000
    socket-timeout-millis: 600000
  prefix: /api
  routes:
    goods:
      # 以/api/goods/ 开头的请求都转发给goods服务
      service-id: goods
      path: /goods/**
    order:
      # 以/api/order/ 开头的请求都转发给order服务
      service-id: order
      path: /order/**